baseurl = "https://glaspie.us"
title = "Infrastructure Guy"
copyright = "Copyright &copy; 2018 - Joseph Glaspie"
canonifyurls = true
theme = "hugo-kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
disqusShortname = "glaspie-us" #Disqus shortname
googleAnalytics = "UA-109425230-2" #Google Analytics ID


[author]
    name = "josephglaspie"
    github = "josephglaspie"
    gitlab = ""
    linkedin = "josephglaspie"
    facebook = ""
    twitter = ""
    instagram = ""

[params]
    tagline = "Aha moments in the life of an Infrastructure Guy"


